# Generated by Django 3.0.4 on 2020-03-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20200310_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.DateTimeField()),
                ('incident_time', models.DateTimeField()),
                ('car_details', models.TextField()),
                ('issued_by', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('nature', models.CharField(max_length=200)),
                ('incident_details', models.TextField()),
            ],
        ),
    ]
