# Generated by Django 3.0.4 on 2020-04-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
