# Generated by Django 3.0.4 on 2020-04-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_reservation_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
