# Generated by Django 2.2.3 on 2020-04-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20200404_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='shop_name',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='shop_number',
            field=models.CharField(default='number', max_length=30),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accept'), ('REJECTED', 'Reject'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
    ]
