# Generated by Django 3.0.4 on 2020-05-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_review',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_review_sum',
            field=models.IntegerField(default=0),
        ),
    ]
